import React from 'react'

const Head = () => {
    return (
        <>
            <title>NextJS 13 Excercise 🐸</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}

export default Head;